### ISSUE TITLE
[Distributed Inference] running under .inference_mode() = assert Dtensor NotImplementedError: Operator aten.matmul.default does not have a sharding strategy registered.

### ISSUE THREAD

**Issue by lessw2020** [pytorch/torchchat#1087]
### 🐛 Describe the bug

run dist inference under .inference_mode():
results in:
~~~
[rank1]:[rank1]: Traceback (most recent call last):
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/distributed/pipelining/stage.py", line 530, in forward_one_chunk
[rank1]:[rank1]:     output = self.forward_maybe_with_nosync(*composite_args, **composite_kwargs)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/distributed/pipelining/stage.py", line 464, in forward_maybe_with_nosync
[rank1]:[rank1]:     out_val = self.submod(*args, **kwargs)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:[rank1]:     return forward_call(*args, **kwargs)
[rank1]:[rank1]:   File "/data/users/less/local/torchchat/build/model_dist.py", line 109, in forward
[rank1]:[rank1]:     x = layer(x, input_pos, freqs_cis, mask)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:[rank1]:     return forward_call(*args, **kwargs)
[rank1]:[rank1]:   File "/data/users/less/local/torchchat/build/model_dist.py", line 152, in forward
[rank1]:[rank1]:     h = x + self.attention(self.attention_norm(x), freqs_cis, mask, input_pos)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:[rank1]:     return forward_call(*args, **kwargs)
[rank1]:[rank1]:   File "/data/users/less/local/torchchat/build/model_dist.py", line 234, in forward
[rank1]:[rank1]:     q: DTensor = self.wq(x)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1788, in _call_impl
[rank1]:[rank1]:     result = forward_call(*args, **kwargs)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 125, in forward
[rank1]:[rank1]:     return F.linear(input, self.weight, self.bias)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_compile.py", line 32, in inner
[rank1]:[rank1]:     return disable_fn(*args, **kwargs)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 636, in _fn
[rank1]:[rank1]:     return fn(*args, **kwargs)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/distributed/_tensor/api.py", line 343, in __torch_dispatch__
[rank1]:[rank1]:     return DTensor._op_dispatcher.dispatch(
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/distributed/_tensor/_dispatch.py", line 121, in dispatch
[rank1]:[rank1]:     return self._custom_op_handlers[op_call](op_call, args, kwargs)  # type: ignore[operator]
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/distributed/_tensor/_dispatch.py", line 52, in decompose_handler
[rank1]:[rank1]:     r = op_call.decompose(*args, **kwargs)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_ops.py", line 756, in decompose
[rank1]:[rank1]:     return self._op_dk(dk, *args, **kwargs)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_compile.py", line 32, in inner
[rank1]:[rank1]:     return disable_fn(*args, **kwargs)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 636, in _fn
[rank1]:[rank1]:     return fn(*args, **kwargs)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/distributed/_tensor/api.py", line 343, in __torch_dispatch__
[rank1]:[rank1]:     return DTensor._op_dispatcher.dispatch(
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/distributed/_tensor/_dispatch.py", line 127, in dispatch
[rank1]:[rank1]:     self.sharding_propagator.propagate(op_info)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/distributed/_tensor/_sharding_prop.py", line 186, in propagate
[rank1]:[rank1]:     output_sharding = self.propagate_op_sharding(op_info.schema)
[rank1]:[rank1]:   File "/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/torch/distributed/_tensor/_sharding_prop.py", line 434, in propagate_op_sharding_non_cached
[rank1]:[rank1]:     raise NotImplementedError(
[rank1]:[rank1]: NotImplementedError: Operator aten.matmul.default does not have a sharding strategy registered.
~~~

### Versions

N/A

**Comment by lessw2020** [comment]
Note - running under torch.no_grad() works fine.
