### ISSUE TITLE
Cannot install ET

### ISSUE THREAD

**Issue by byjlw** [pytorch/torchchat#1103]
### 🐛 Describe the bug

Command to install and Setup ET throws an error
`./torchchat/utils/scripts/install_et.sh`

```

  CMake Warning at build/Utils.cmake:241 (message):
    Failed to retrieve buck2 version: [Errno 2] No such file or directory:
    'buck2'.

    Downloading buck2 from
    https://github.com/facebook/buck2/releases/download/2024-05-15/buck2-aarch64-apple-darwin.zst...


    Traceback (most recent call last):

      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1298, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1344, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1293, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1052, in _send_output
        self.send(msg)
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 990, in send
        self.connect()
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1470, in connect
        self.sock = self._context.wrap_socket(self.sock,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
        return self.sslsocket_class._create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1104, in _create
        self.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1382, in do_handshake
        self._sslobj.do_handshake()

    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate
    verify failed: unable to get local issuer certificate (_ssl.c:1006)



    During handling of the above exception, another exception occurred:



    Traceback (most recent call last):

      File "/Users/jessewhite/Documents/source/torchchat/et-build/src/executorch/build/resolve_buck.py", line 224, in <module>
        main()
      File "/Users/jessewhite/Documents/source/torchchat/et-build/src/executorch/build/resolve_buck.py", line 216, in main
        resolved_path_or_error = resolve_buck2(args)
                                 ^^^^^^^^^^^^^^^^^^^
      File "/Users/jessewhite/Documents/source/torchchat/et-build/src/executorch/build/resolve_buck.py", line 198, in resolve_buck2
        urllib.request.urlretrieve(buck2_archive_url, archive_file.name)
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 241, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
                                ^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
        response = self._open(req, data)
                   ^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
        result = func(*args)
                 ^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
        raise URLError(err)

    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]
    certificate verify failed: unable to get local issuer certificate
    (_ssl.c:1006)>

  Call Stack (most recent call first):
    CMakeLists.txt:318 (resolve_buck2)


  -- Killing buck2 daemon
  -- executorch: Generating source lists
  -- executorch: Generating source file list /Users/jessewhite/Documents/source/torchchat/et-build/src/executorch/pip-out/temp.macosx-10.9-universal2-cpython-311/cmake-out/executorch_srcs.cmake
  Error while generating /Users/jessewhite/Documents/source/torchchat/et-build/src/executorch/pip-out/temp.macosx-10.9-universal2-cpython-311/cmake-out/executorch_srcs.cmake. Exit code: 1
  Output:

  Error:
  Traceback (most recent call last):
    File "/Users/jessewhite/Documents/source/torchchat/et-build/src/executorch/build/extract_sources.py", line 218, in <module>
      main()
    File "/Users/jessewhite/Documents/source/torchchat/et-build/src/executorch/build/extract_sources.py", line 203, in main
      target_to_srcs[name] = sorted(target.get_sources(graph, runner))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/jessewhite/Documents/source/torchchat/et-build/src/executorch/build/extract_sources.py", line 116, in get_sources
      sources: set[str] = set(runner.run(["cquery", query]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/jessewhite/Documents/source/torchchat/et-build/src/executorch/build/buck_util.py", line 26, in run
      cp: subprocess.CompletedProcess = subprocess.run(
                                        ^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
      with Popen(*popenargs, **kwargs) as process:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1953, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'buck2'

  CMake Error at build/Utils.cmake:191 (message):
    executorch: source list generation failed
  Call Stack (most recent call first):
    CMakeLists.txt:327 (extract_sources)


  -- Configuring incomplete, errors occurred!
  error: command '/Users/jessewhite/Documents/source/torchchat/.venv/bin/cmake' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Building wheel for executorch (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/jessewhite/Documents/source/torchchat/.venv/bin/python3.11 /Users/jessewhite/Documents/source/torchchat/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /var/folders/7k/2n2lk60d5n57_33yh299tt0c0000gn/T/tmprw3xt79q
  cwd: /Users/jessewhite/Documents/source/torchchat/et-build/src/executorch
  Building wheel for executorch (pyproject.toml) ... error
  ERROR: Failed building wheel for executorch
Failed to build executorch
ERROR: Could not build wheels for executorch, which is required to install pyproject.toml-based projects

```

### Versions

Operating System Information
Darwin MadMax.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:33:00 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6031 arm64

Python Version
Python 3.11.8

PIP Version
pip 24.0 from /Users/jessewhite/Documents/source/torchchat/.venv/lib/python3.11/site-packages/pip (python 3.11)

Installed Packages
absl-py==2.1.0
accelerate==0.34.0
aiohappyeyeballs==2.4.0
aiohttp==3.10.5
aiosignal==1.3.1
altair==5.4.1
annotated-types==0.7.0
anyio==4.4.0
attrs==24.2.0
blinker==1.8.2
blobfile==3.0.0
cachetools==5.5.0
certifi==2024.8.30
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
cmake==3.30.2
colorama==0.4.6
DataProperty==1.0.1
datasets==2.21.0
dill==0.3.8
distro==1.9.0
evaluate==0.4.2
filelock==3.15.4
Flask==3.0.3
frozenlist==1.4.1
fsspec==2024.6.1
gguf==0.10.0
gitdb==4.0.11
GitPython==3.1.43
h11==0.14.0
httpcore==1.0.5
httpx==0.27.2
huggingface-hub==0.24.6
idna==3.8
itsdangerous==2.2.0
Jinja2==3.1.4
jiter==0.5.0
joblib==1.4.2
jsonlines==4.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
lm_eval==0.4.2
lxml==5.3.0
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mbstrdecoder==1.1.3
mdurl==0.1.2
more-itertools==10.4.0
mpmath==1.3.0
multidict==6.0.5
multiprocess==0.70.16
narwhals==1.6.0
networkx==3.3
ninja==1.11.1.1
nltk==3.9.1
numexpr==2.10.1
numpy==1.26.4
openai==1.43.0
packaging==24.1
pandas==2.2.2
pathvalidate==3.2.1
peft==0.12.0
pillow==10.4.0
portalocker==2.10.1
protobuf==5.28.0
psutil==6.0.0
pyarrow==17.0.0
pybind11==2.13.5
pycryptodomex==3.20.0
pydantic==2.8.2
pydantic_core==2.20.1
pydeck==0.9.1
Pygments==2.18.0
pytablewriter==1.2.0
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.2
referencing==0.35.1
regex==2024.7.24
requests==2.32.3
rich==13.8.0
rouge_score==0.1.2
rpds-py==0.20.0
sacrebleu==2.4.3
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.14.1
sentencepiece==0.2.0
six==1.16.0
smmap==5.0.1
snakeviz==2.2.0
sniffio==1.3.1
sqlitedict==2.1.0
streamlit==1.38.0
sympy==1.13.1
tabledata==1.3.3
tabulate==0.9.0
tcolorpy==0.1.6
tenacity==8.5.0
threadpoolctl==3.5.0
tiktoken==0.7.0
timm==1.0.7
tokenizers==0.19.1
toml==0.10.2
tomli==2.0.1
torch==2.5.0.dev20240716
torchao @ git+https://github.com/pytorch/ao.git@e11201a62669f582d81cdb33e031a07fb8dfc4f3
torchaudio==2.4.0.dev20240716
torchsr==1.0.4
torchvision==0.20.0.dev20240716
tornado==6.4.1
tqdm==4.66.5
tqdm-multiprocess==0.0.11
transformers==4.42.4
typepy==1.3.2
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.2
Werkzeug==3.0.4
word2number==1.1
xxhash==3.5.0
yarl==1.9.7
zstandard==0.23.0
zstd==1.5.5.1

PyTorch Version
2.5.0.dev20240716

Collection Complete

**Comment by byjlw** [comment]
Certs were out of date

Resolution Steps
--------------------------
The error you're encountering, SSLCertVerificationError, indicates a problem with SSL certificate verification when attempting to connect securely to GitHub. This usually happens when Python cannot find or trust the root certificates needed to verify GitHub's SSL certificate. Here are a few steps you can take to resolve this issue:

Ran this command and everything started working
`/Applications/Python\ 3.11/Install\ Certificates.command`
