### ISSUE TITLE
unable to run torchchat on CentOS 9

### ISSUE THREAD

**Issue by byjlw** [pytorch/torchchat#1141]
### 🐛 Describe the bug

After running the help command after running the install script i get the following error
```
(.venv) [byjlw@devvm2168.cco0 ~/local/torchchat (main)]$ python3 torchchat.py --help
Traceback (most recent call last):
  File "/data/users/byjlw/torchchat/torchchat.py", line 12, in <module>
    from torchchat.cli.cli import (
  File "/data/users/byjlw/torchchat/torchchat/cli/cli.py", line 14, in <module>
    import torch
  File "/data/users/byjlw/torchchat/.venv/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /data/users/byjlw/torchchat/.venv/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkAddData_12_1, version libnvJitLink.so.12
(.venv) [byjlw@devvm2168.cco0 ~/local/torchchat (main)]$ 

```

### Versions

command fails to output torch version with the same issue

```
PyTorch Version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/users/byjlw/torchchat/.venv/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /data/users/byjlw/torchchat/.venv/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkAddData_12_1, version libnvJitLink.so.12
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/users/byjlw/torchchat/.venv/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /data/users/byjlw/torchchat/.venv/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkAddData_12_1, version libnvJitLink.so.12
(.venv) [byjlw@devvm2168.cco0 ~/local/torchchat (main)]$ 

```

**Comment by Gasoonjia** [comment]
This one is more like a pytorch installation error. can you try

```
python -c "import torch; print(torch.__version__)"
```

and see what happens?

**Comment by Gasoonjia** [comment]
any error msg came out after running 
```
./install/install_requirements.sh
```

**Comment by byjlw** [comment]
My Python3.10 pathing was messed up some how. I figured it out by following the recommended fix in this issue. https://github.com/pytorch/pytorch/issues/111469

I reinstalled python3.10 and everything worked.
