### ISSUE TITLE
AttributeError: partially initialized module 'torchvision' has no attribute 'extension'

### ISSUE THREAD

**Issue by kwen2501** [pytorch/torchchat#1158]
### 🐛 Describe the bug

I was trying to use a develop version of pytorch, while other torch library are from the pinned nightly as in `install_requirements.sh`.

```
torch                     2.6.0a0+gitf28a873           dev_0    <develop>
torchao                   0.5.0                    pypi_0    pypi
torchfix                  0.4.0                    pypi_0    pypi
torchtune                 0.3.0.dev20240910+cu121          pypi_0    pypi
torchvision               0.20.0.dev20240814+cu121          pypi_0    pypi
```

But I hit the following error from torchvision:

```
Traceback (most recent call last):
  File "/home/kw2501/local/torchchat/dist_run.py", line 35, in <module>
    from torchchat.cli.builder import _initialize_tokenizer, TokenizerArgs
  File "/home/kw2501/local/torchchat/torchchat/cli/builder.py", line 37, in <module>
    from torchchat.model import Model, ModelType
  File "/home/kw2501/local/torchchat/torchchat/model.py", line 31, in <module>
    from torchtune.models.flamingo import flamingo_decoder, flamingo_vision_encoder
  File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torchtune/models/flamingo/__init__.py", line 7, in <module>
    from ._component_builders import flamingo_decoder, flamingo_vision_encoder
  File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torchtune/models/flamingo/_component_builders.py", line 7, in <module>
    from torchtune.models.clip import clip_vision_encoder, clip_mlp
  File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torchtune/models/clip/__init__.py", line 14, in <module>
    from ._transform import CLIPImageTransform
  File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torchtune/models/clip/_transform.py", line 11, in <module>
    import torchvision
  File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
  File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torchvision/_meta_registrations.py", line 26, in <module>
    def meta_roi_align(input, rois, spatial_scale, pooled_height, pooled_width, sampling_ratio, aligned):
  File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torchvision/_meta_registrations.py", line 18, in wrapper
    if torchvision.extension._has_ops():
AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)
```

### Versions

main

**Comment by Gasoonjia** [comment]
I met a similar issue before; my issue was caused by torch and torchvision version async.
Have you tried to 
a. also uses a develop version torchvision
b. uses the same nightly version for both torch and torchvision that meet your requirement?
