### ISSUE TITLE
Can't install using Python 3.12.3

### ISSUE THREAD

**Issue by byjlw** [pytorch/torchchat#1289]
### 🐛 Describe the bug

error out when running the install sh script

```
Building wheels for collected packages: zstd
  Building wheel for zstd (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for zstd (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /tmp/pip-build-env-r9_19l5m/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_ext
      building 'zstd' extension
      creating build/temp.linux-x86_64-cpython-312/src
      creating build/temp.linux-x86_64-cpython-312/zstd/lib/common
      creating build/temp.linux-x86_64-cpython-312/zstd/lib/compress
      creating build/temp.linux-x86_64-cpython-312/zstd/lib/decompress
      x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -I/home/warden/source/torchchat/.venv/include -I/usr/include/python3.12 -c src/python-zstd.c -o build/temp.linux-x86_64-cpython-312/src/python-zstd.o -O2 -DVERSION=1.5.5.1 -DDYNAMIC_BMI2=0 -DZSTD_DISABLE_ASM=1 -DZSTD_MULTITHREAD=1 -Izstd/lib -Izstd/lib/common -Izstd/lib/compress -Izstd/lib/decompress -DZSTD_TRACE=0
      src/python-zstd.c:40:10: fatal error: Python.h: No such file or directory
         40 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for zstd
Failed to build zstd
ERROR: Could not build wheels for zstd, which is required to install pyproject.toml-based projects
````

### Versions

Operating System Information
Linux Furiosa 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

Python Version
Python 3.12.3

PIP Version
pip 24.0 from /home/warden/source/torchchat/.venv/lib/python3.12/site-packages/pip (python 3.12)

Installed Packages

PyTorch Version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'

**Comment by dbort** [comment]
Looks like the zstd package might depend on the python-dev/python-devel package being installed on the system https://stackoverflow.com/a/21530768

**Comment by leseb** [comment]
For what is worth torchchat only supports Python 3.10.x or .3.11.x AFAIK.
