### ISSUE TITLE
Multimodal Eval Enablement (Looking for Developer to Implement Design)

### ISSUE THREAD

**Issue by Olivia-liu** [pytorch/torchchat#1334]
### 🚀 The feature, motivation and pitch

***Please note that since the actual implementation is going to be simple, and the design has already been reviewed, the purpose of this GitHub Issue is to look for a developer to implement this feature ASAP.***

LLM eval stands for the process of assessing the perplexity, performance and capabilities of LLMs, usually by having the model complete one or a series of tasks and assigning them scores. Torchchat is already using EleutherAI’s [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness) to do eval on text LLM ([code pointer](https://github.com/pytorch/torchchat/blob/11dcbebe6bd2ee933f7302b4e14baa23761abc0c/torchchat/usages/eval.py#L198)). Recently, torchtune has worked with EleutherAI to enable eval on text-image models in the harness, and has integrated this feature into torchtune ([code pointer](https://github.com/pytorch/torchtune/blob/d0c6460b51fc18245b3da0220568e10b3de06b63/recipes/eleuther_eval.py#L40)). Torchchat wants to just copy that solution from torchtune for text-image models.

Without the ability to do eval on multimodal LLMs, the enablement of multimodal LLMs on torchchat is incomplete. It’s critical to understand how well torchchat performs with image inputs. 

## Assumptions

* The eval for text LLMs is already enabled on torchchat. Code pointer to the [core eval function](https://github.com/pytorch/torchchat/blob/11dcbebe6bd2ee933f7302b4e14baa23761abc0c/torchchat/usages/eval.py#L172) and the [main function](https://github.com/pytorch/torchchat/blob/11dcbebe6bd2ee933f7302b4e14baa23761abc0c/torchchat/usages/eval.py#L226).
* The Llama 3.2-11b multimodal model has been onboarded to torchchat, and in the future there will be more multimodal LLMs on torchchat. 
* EleutherAI’s [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness) has enabled eval on llama3.2-11b, thus we don’t need to make code changes in EleutherAI repo.

## The Main Goal
A torchchat user can run eval on the llama 3.2-11b model (which image-text-in, text-out). Note that we don’t need to worry about the internals of how the eval happens because we will only be calling the EleutherAI’s eval libraries and report the metrics it returns. 

The user interface will be a commandline `python torchchat.py eval <model-name>` with additional arguments specifying detailed requirements for the eval tasks.

The result will be printed out on the terminal which include the following metrics:
 * Tasks that have been run 
 * The score to each task 
 * The time it took to run each task

### RFC (Optional)

# Design

## Overview

In this design, the multimodal eval in torchchat will borrow from the implementation of multimodal eval in torchtune which utilizes EleutherAI’s [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness). The reason we can do this is that torchchat uses the same Llama 3.2-11b model definition as torchtune. 

#### [Preferred] Approach A: import the implementation of `HFMultimodalLM` from torchtune directly 
The easiest implementation is to import the implementation of <code>HFMultimodalLM </code>directly from torchtune, then call <code>evaluate()</code> with this wrapper class passed in. </em>

Here’s torchtune’s implementation of `HFMultimodalLM`: [code pointer](https://github.com/pytorch/torchtune/blob/ced1a840300b1ab550dac4fc2054b187f5b45c8c/recipes/eleuther_eval.py#L68).

*Pseudocode:*
```
# In eval.py
from torchtune.recipes.eleuther_eval import _VLMEvalWrapper

if model is text-based:
   do the existing text-based model eval
elif model is text-image-based:
   eval_results = evaluate(_VLMEvalWrapper(...))
```

The pros and cons of this solution is discussed in the following “Alternatives Discussion” section. This solution should be the one to start with given how quick it can enable multimodal eval on torchchat. If for some unforeseen reason that it doesn’t work, then take the following approach that requires more work.

#### Approach B: copy the implementation of `HFMultimodalLM` from torchtune

1. Creating a wrapper class that overrides class <code>[HFMultimodalLM](https://github.com/EleutherAI/lm-evaluation-harness/blob/0845b588303f1f59af98dd1c5bdbd78a9e75a1e2/lm_eval/models/hf_vlms.py#L30)</code>, which is an abstract Hugging Face model class for multimodal models. The implementation of this class can be copied from torchtune, [code pointer](https://github.com/pytorch/torchtune/blob/ced1a840300b1ab550dac4fc2054b187f5b45c8c/recipes/eleuther_eval.py#L68).
2. Then call <code>evaluate()</code> with this wrapper class passed in. 

*Pseudocode:*
```
# In eval.py
from lm_eval.models.hf_vlms import HFMultimodalLM
from lm_eval.evaluator import evaluate

class VLMEvalWrapper(HFMultimodalLM):
   ...# implementation

if model is text-based:
   do the existing text-based model eval
elif model is text-image-based:
   eval_results = evaluate(VLMEvalWrapper(...))
```

### The Commandline Arguments

User command should be `python torchchat.py eval llama3.2-11b` + some optional arguments.

In terms of implementation, reuse the same cli entry point as the text eval: [torchchat.py](https://github.com/pytorch/torchchat/blob/77774d2345dee150d7bdc2dbd22529cbde388ed7/torchchat.py#L89), [eval.py](https://github.com/pytorch/torchchat/blob/77774d2345dee150d7bdc2dbd22529cbde388ed7/torchchat/usages/eval.py#L226). Then in [def eval()](https://github.com/pytorch/torchchat/blob/77774d2345dee150d7bdc2dbd22529cbde388ed7/torchchat/usages/eval.py#L172), have an if-else to decide which eval wrapper (`GPTFastEvalWrapper` or the new `VLMEvalWrapper`) to use based on model type. 

## Alternatives Discussion

Discuss the pros and cons of importing torchtune’s implementation directly

Pro: 

1. Easy to implement because it’s just an import
2. Consistency between torchchat and torchtune
3. Easy maintenance for us
4. Torchtune has a better relationship with EleutherAI 

Cons:

1. Hard to customize the implementation for torchchat’s needs
2. For some models, we use model definitions that are different from torchtune’s
3. We rely on the compatibility on their side
4. We have more dependency on torchtune

## Testing & Tooling Plan

Run command `python torchchat.py eval llama3.2-11b` with different parameter combinations. 

The expected output is the tasks that have been run, their scores and the time it took to run each task.

**Comment by Gasoonjia** [comment]
Thanks Olivia for the RFC!

I would like to provide the third option: creating our own `VLMEvalWrapper`, but instead of coping-and-pasting the implementation of `HFMultimodalLM` from `torchtune`, we can make it inherit from `HFMultimodalLM`.

I think such way can have following benefits:

1. Easy to implement. First version we can make `VLMEvalWrapper` a simple wrapper on the top of `HFMultimodalLM` without any other add-ons, so that it is just an import at very beginning
2. Easy to maintain for us and deduplicate code across different repos
3. Make `torchchat` as lean as possible. The starting point of torchchat would always a small codebase showcasing the ability to run large language models (LLMs) seamlessly.
4. Keep the customizing ability. We can always add new functions or even overwrite the existing functions for our own model definitions or other purpose
5. Make eval.py lean and easy to maintain.  Personally, I would like to eliminate as much if-else statement as possible during the validating process, to avoid bloated code and unclear logic (that's what we plan to do on generate.py and build.py).  Creating our own `VLMEvalWrapper` can help us create a structural validation logic (e.g. absorb current text-only validation logic into the class.)


Please let me how's that feel

**Comment by Vishnu-sai-teja** [comment]
I would like to take this up, can try to help out in this.

**Comment by Olivia-liu** [comment]
> Approach A

**Comment by Olivia-liu** [comment]
> Thanks Olivia for the RFC!
> 
> I would like to provide the third option: creating our own `VLMEvalWrapper`, but instead of coping-and-pasting the implementation of `HFMultimodalLM` from `torchtune`, we can make it inherit from `HFMultimodalLM`.
> 
> I think such way can have following benefits:
> 
> 1. Easy to implement. First version we can make `VLMEvalWrapper` a simple wrapper on the top of `HFMultimodalLM` without any other add-ons, so that it is just an import at very beginning
> 2. Easy to maintain for us and deduplicate code across different repos
> 3. Make `torchchat` as lean as possible. The starting point of torchchat would always a small codebase showcasing the ability to run large language models (LLMs) seamlessly.
> 4. Keep the customizing ability. We can always add new functions or even overwrite the existing functions for our own model definitions or other purpose
> 5. Make eval.py lean and easy to maintain.  Personally, I would like to eliminate as much if-else statement as possible during the validating process, to avoid bloated code and unclear logic (that's what we plan to do on generate.py and build.py).  Creating our own `VLMEvalWrapper` can help us create a structural validation logic (e.g. absorb current text-only validation logic into the class.)
> 
> Please let me how's that feel

I think this makes a lot of sense! Thanks for writing it up. Let's prefer this over the Approach B above. I'll still prefer to get Approach A work first if possible, given how simple that can be.

**Comment by Olivia-liu** [comment]
> I would like to take this up, can try to help out in this.

@Vishnu-sai-teja That'd be awesome! Please go ahead and take it. Looking forward to it!

**Comment by Olivia-liu** [comment]
> > I would like to take this up, can try to help out in this.
> 
> @Vishnu-sai-teja That'd be awesome! Please go ahead and take it. Looking forward to it!

@Vishnu-sai-teja Once you have an ETA for a PR, please kindly let us know!

**Comment by Vishnu-sai-teja** [comment]
Hi @Olivia-liu,

I plan to submit the initial PR in 3-4 days. Here's the brief timeline:

Day 1-2: Study existing eval implementation and HFMultimodalLM class
Day 3-4: Implement VLMEvalWrapper and integrate with eval.py, along with basic testing

As a newbie to the codebase, this timeline ensures a quality implementation while I thoroughly understand it. Let me know if you need any adjustments.

Thanks!

**Comment by Jack-Khuu** [comment]
Sounds great, thanks for contributing!

@Olivia-liu is OOO for a bit, so I can help with any questions/blockers you might run into

**Comment by Gasoonjia** [comment]
You are also welcome to join our slack channel to chat with us.

Please see https://github.com/pytorch/torchchat?tab=readme-ov-file#community-contributions for more info.

**Comment by byjlw** [comment]
@Vishnu-sai-teja, hey checking in! Still able to take this one on?

**Comment by Vishnu-sai-teja** [comment]
> @Vishnu-sai-teja, hey checking in! Still able to take this one on?

Hey tried to implement both ways, getting errors in the torch time imports while running the evaluation for the torchchat.

**Comment by byjlw** [comment]
> > @Vishnu-sai-teja, hey checking in! Still able to take this one on?
> 
> Hey tried to implement both ways, getting errors in the torch time imports while running the evaluation for the torchchat.

Easiest to discuss if you join the slack channel. 

But we can do it here if that works best. 

Can you share a link to your branch, the commands you ran and the full output you got?

**Comment by Gasoonjia** [comment]
hi @Vishnu-sai-teja just wanna check if everything is ok here.
If you need help, feel free to share branch or any info here, or using the slack channel wo share with us.

**Comment by Olivia-liu** [comment]
Looking for new assignee(s) of this Issue

**Comment by anirudhs001** [comment]
Hey @Olivia-liu, I'd like to take this up if it's still not done yet.

**Comment by Jack-Khuu** [comment]
Would love for you to give it a shot, feel free to tag us with any questions/clarification

If you haven't already you should join the torchchat-contributer channel in the PyTorch slack too: https://github.com/pytorch/torchchat?tab=readme-ov-file#community-contributions

**Comment by anirudhs001** [comment]
Hey
This likely is a noobie question, but how do I import `_VLMEvalWrapper` from torchtune?
I installed torchtune via pip and the installed package only has the contents from https://github.com/pytorch/torchtune/tree/main/torchtune. Can't see recipes and other folders.

Here's a screenshot of the contents of the torchtune package inside my virtual env:
<img width="268" alt="Image" src="https://github.com/user-attachments/assets/fe11836b-6dc0-4285-97d7-88ffdfe888dd" />

**Comment by Olivia-liu** [comment]
Hi @anirudhs001 that's a good question. I found out that we're not supposed to import from torchtune's recipes directory: https://github.com/pytorch/torchtune/blob/059cad9c1c0b684ec095634992468eca18bbd395/recipes/__init__.py#L20

Given that, that's take the copy-paste approach (Approach B).

**Comment by anirudhs001** [comment]
Hey @Olivia-liu 

I have made a [WIP PR](https://github.com/anirudhs001/torchchat/pull/1/files) in my fork. Need your help on a few things:
1. Our [requirements.txt](https://github.com/pytorch/torchchat/blob/53a100462cdef536c7497026f26cce33290ec659/install/requirements.txt#L37) right now has `lm_eval==0.4.2`. The support for multi-modal models came in lm_eval since `v0.4.5` (This is the version in which [hf_vlms.py](https://github.com/EleutherAI/lm-evaluation-harness/blob/v0.4.5/lm_eval/models/hf_vlms.py), the file that defines `HFMultimodalLM` was added to the repo). I have updated requirements.txt to use `v0.4.5`. Is this ok, or should we define `HFMultimodalLM` ourselves too?
2. The [Llama-3.2-Vision.json](https://github.com/pytorch/torchchat/blob/53a100462cdef536c7497026f26cce33290ec659/torchchat/model_params/Llama-3.2-11B-Vision.json#L3C21-L3C25) specifies using tiktoken as the tokenizer. AFAICT, tiktoken only supports tokenising text (don't see a mention of image or anything related [here](https://github.com/openai/tiktoken/blob/main/tiktoken/core.py)). I have added [`Llama3VisionTransform`](https://github.com/pytorch/torchtune/blob/8c9235e2b10cc9e1aa381aaec4b992dbf52c48da/torchtune/models/llama3_2_vision/_transform.py#L17C7-L17C28) from torchtune to create the tokenizer for now.
3. The only multi-modal model supported right now is the 11b llama-3.2. I get OOM errors when I load a model this big with fp32, and the generation with bf16 takes too long. Is there an easy way to add the support for smaller multi-modal models, or any other place I can test the changes?

**Comment by Jack-Khuu** [comment]
Hi @anirudhs001, I'll be taking over support for Olivia

1) Totally works to bump the requirements!
2) Sgtm, we can work with torchtune on how we want to approach this once we get an e2e flow working
3) May I ask how much memory your machine has? We were looking at quantizing 11B, but never got around to pushing it through (if you're interested in a fun little detour, we'd gladly take the help)  
  - Also how slowly did bf16 run? For the sake of starting off, we can do 2 samples and reduced max_seq_len

Also if you haven't already, hop into our slack channel: https://pytorch.slack.com/archives/C07UMLFQHT6 (torchchat-contributers)

**Comment by anirudhs001** [comment]
Hey @Jack-Khuu 
I am using a 32 Gb M2 Max Macbook pro. 
I have filled the contribution form, but can't open the slack channel with any of my accounts. Do I need to something else too?
Any pointers on what I can do to help with the quanitization?

Tried messing around with `max_seq_len`. Left my laptop running overnight with 4096 but didn't get anything out. Got this error with 200:
```
(venv) (base) anirudhsingh@Anirudhs-MacBook-Pro-4 torchchat % python torchchat.py eval Llama-3.2-mm --dtype bf16 --task mmmu_val_art --limit 1 --modality text-image --max-seq-length 200
NumExpr defaulting to 12 threads.
PyTorch version 2.7.0.dev20250124 available.
Looking for libcustom_ops_aot_lib.so in /Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/executorch
Loading custom ops library: /Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/executorch/extension/llm/custom_ops/libcustom_ops_aot_lib.dylib
Unable to import torchao experimental quant_api with error:  [Errno 2] No such file or directory: '/Users/anirudhsingh/MISC/playground/torchchat/torchao-build/src/ao/torchao/experimental/quant_api.py'
Modality of model=text-image
Using device=mps
Loading model...
Time to load model: 70.82 seconds
-----------------------------------------------------------
Building contexts for mmmu_val_art on rank 0...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 5322.72it/s]
Running generate_until requests
Running generate_until requests with text+image input:   0%|                                                               | 0/1 [00:00<?, ?it/s]Time to run eval: 86.67s.
Traceback (most recent call last):
  File "/Users/anirudhsingh/MISC/playground/torchchat/torchchat.py", line 100, in <module>
    eval_main(args)
  File "/Users/anirudhsingh/MISC/playground/torchchat/torchchat/usages/eval.py", line 593, in main
    result = multi_model_eval(
  File "/Users/anirudhsingh/MISC/playground/torchchat/torchchat/usages/eval.py", line 523, in multi_model_eval
    eval_results = evaluate(
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/lm_eval/utils.py", line 397, in _wrapper
    return fn(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/lm_eval/evaluator.py", line 500, in evaluate
    resps = getattr(lm, reqtype)(cloned_reqs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/lm_eval/models/hf_vlms.py", line 691, in generate_until
    cont = self._model_multimodal_generate(inputs, stop=until, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/torchchat/usages/eval.py", line 401, in _model_multimodal_generate
    logits = self.model(prompt, **batch)[:, -1]
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1749, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1760, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/torchchat/model.py", line 595, in forward
    return self.model(
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1749, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1760, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torchtune/modules/model_fusion/_deep_fusion.py", line 205, in forward
    output = self.decoder(
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1749, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1760, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torchtune/modules/transformer.py", line 635, in forward
    h = layer(
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1749, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1760, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torchtune/modules/transformer.py", line 122, in forward
    attn_out = self.attn(h, h, mask=mask, input_pos=input_pos)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1749, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1760, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torchtune/modules/attention.py", line 243, in forward
    q = self.pos_embeddings(q, input_pos=input_pos)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1749, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1760, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/torchtune/models/llama3_1/_position_embeddings.py", line 171, in forward
    xshaped = x.float().reshape(*x.shape[:-1], -1, 2)
RuntimeError: cannot reshape tensor of 0 elements into shape [1, 0, 32, -1, 2] because the unspecified dimension size -1 can be any value and is ambiguous
Running generate_until requests with text+image input:   0%|                                                               | 0/1 [01:13<?, ?it/s]
(venv) (base) anirudhsingh@Anirudhs-MacBook-Pro-4 torchchat % 
```
Will try to look deeper in a day or two.

**Comment by Jack-Khuu** [comment]
@anirudhs001 Are you able to access the larger PyTorch Slack? https://github.com/pytorch/pytorch?tab=readme-ov-file#communication

I can add you in the channel that way (Or if I have can send you email, I'll send a direct invite)

> 32 Gb M2 Max

Interesting, this should be plenty powerful. 

Getting a tensor mismatch is where the fun part starts: seems to suggest a disconnect between how things work in torchtune and what we're expecting in torchchat. 

Were you able to get the torchtune eval running?

**Comment by Jack-Khuu** [comment]
Can you try out this form?
https://docs.google.com/forms/d/e/1FAIpQLSeADnUNW36fjKjYzyHDOzEB_abKQE9b6gqqW9NXse6O0MWh0A/viewform

> I'll try to see what we do differently.

Sweet, feel free to spin up an issue in torchtune with this issue/me if you run into anything funky

**Comment by anirudhs001** [comment]
Hey @Jack-Khuu,

I’ve filled out that form a couple of times now but still can’t sign into the [Slack workspace](https://pytorch.slack.com/?redir=%2Farchives%2FC07UMLFQHT6%3Fname%3DC07UMLFQHT6).

That aside, it’s working now. I’ve created [PR #1499](https://github.com/pytorch/torchchat/pull/1499).

**Comment by Jack-Khuu** [comment]
That's amazing! I'll take a look on Monday

@anirudhs001 hmm if you don't mind, can you add me via [linkedin](https://www.linkedin.com/in/jack-khuu-uwcse/)? I'll try to add you that way
