### ISSUE TITLE
[PAPERCUTS] error message repeated ad nauseam

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/torchchat#543]
I get it -- maybe the error is `aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'`

Seriously, though - I got it after the first error meesage about that, and certainly after the 5th?  I'll assume it's for each call site?  It's probably onerus to keep track of every error, especially at the point where the error is emitted.  But I presume the message goes thru a common reporting site... maybe we can just keep track of the previous error message, and if it's the same as the immediately precedcing, we start a counter and emit 
[repeated n times] when the error changes.

Or we compute a hash of each message, and add up counts for all messages after the first error, dumping a second instance at the end with a count?

One more thing -- can we put a filename and an error line?  I recall that Soumith said in another meeting that we have that info for IR traces?

```
(py311) mikekg@mikekg-mbp torchchat %  python export.py --checkpoint-path ${MODEL_PATH} --temperature 0  --quantize '{"linear:int4": {"groupsize": 128}}' --output-pte mode.pte
[...]
   %aten__weight_int4pack_mm_default_42 : [num_users=1] = call_function[target=executorch.exir.dialects.edge._ops.aten._weight_int4pack_mm.default](args = (%aten_view_copy_default_144, %b_output_weight, 128, %b_output_scales_and_zeros), kwargs = {})
    %aten_view_copy_default_145 : [num_users=1] = call_function[target=executorch.exir.dialects.edge._ops.aten.view_copy.default](args = (%aten__weight_int4pack_mm_default_42, [1, 1, 32000]), kwargs = {})
    return (getitem_1, getitem_2, getitem_4, getitem_5, getitem_7, getitem_8, getitem_10, getitem_11, getitem_13, getitem_14, getitem_16, getitem_17, aten_view_copy_default_145)
WARNING:executorch.backends.xnnpack.partition.xnnpack_partitioner:Nothing can be partitioned!
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
INFO:root:Failed converting '<EdgeOpOverload: aten._weight_int4pack_mm.default>: schema = aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor' to its out variant with error: 'SchemaKind.out variant of operator aten::_weight_int4pack_mm can't be found. We've found the schemas of all the overloads: ['aten::_weight_int4pack_mm(Tensor self, Tensor mat2, int qGroupSize, Tensor qScaleAndZeros) -> Tensor']'
Traceback (most recent call last):
  File "/Users/mikekg/qops/torchchat/export.py", line 111, in <module>
    main(args)
  File "/Users/mikekg/qops/torchchat/export.py", line 91, in main
    export_model_et(
  File "/Users/mikekg/qops/torchchat/export_et.py", line 98, in export_model
    export_program = edge_manager.to_executorch(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/miniconda3/envs/py311/lib/python3.11/site-packages/executorch/exir/program/_program.py", line 899, in to_executorch
    new_gm_res = p(new_gm)
                 ^^^^^^^^^
  File "/Users/mikekg/miniconda3/envs/py311/lib/python3.11/site-packages/torch/fx/passes/infra/pass_base.py", line 40, in __call__
    res = self.call(graph_module)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/miniconda3/envs/py311/lib/python3.11/site-packages/executorch/exir/passes/__init__.py", line 423, in call
    raise RuntimeError(f"Missing out variants: {missing_out_vars}")
RuntimeError: Missing out variants: {'aten::_weight_int4pack_mm'}

**Comment by byjlw** [comment]
No longer an issue.
