### ISSUE TITLE
Export and run exported model completely broken - RuntimeError: loading method forward failed with error 0x20

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/torchchat#662]
Note that I'm using 3.11, I've also built with that, though.  And this used to work, and we have it in CI...

```
(py311) mikekg@mikekg-mbp torchchat % python3 torchchat.py export llama3 --dtype float32 --quantize config/data/mobile.json --output-pte-path model.pte
[...]
Found 225 subgraphs to be partitioned.
/Users/mikekg/miniconda3/envs/py311/lib/python3.11/site-packages/executorch/exir/emit/_emitter.py:1474: UserWarning: Mutation on a buffer in the model is detected. ExecuTorch assumes buffers that are mutated in the graph have a meaningless initial state, only the shape and dtype will be serialized.
  warnings.warn(
The methods are:  {'forward'}
(py311) mikekg@mikekg-mbp torchchat % python3 torchchat.py generate llama3 --dtype float32 --quantize config/data/mobile.json --pte-path model.pte
Warning: checkpoint path ignored because an exported DSO or PTE path specified
Warning: checkpoint path ignored because an exported DSO or PTE path specified
Using device=cpu Apple M1 Max
Loading model...
Time to load model: 6.13 seconds
[program.cpp:130] InternalConsistency verification requested but not available
[method.cpp:66] Backend XnnpackBackend is not registered.
Traceback (most recent call last):
  File "/Users/mikekg/u4b/torchchat/build/builder.py", line 408, in _initialize_model
    model = PTEModel(model.config, builder_args.pte_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/u4b/torchchat/build/model_et.py", line 10, in __init__
    self.model_ = exec_lib._load_for_executorch(str(path))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: loading method forward failed with error 0x20

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mikekg/u4b/torchchat/torchchat.py", line 146, in <module>
    generate_main(args)
  File "/Users/mikekg/u4b/torchchat/generate.py", line 780, in main
    _main(
  File "/Users/mikekg/u4b/torchchat/generate.py", line 535, in _main
    model = _initialize_model(builder_args, quantize, tokenizer)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/u4b/torchchat/build/builder.py", line 410, in _initialize_model
    raise RuntimeError(f"Failed to load ET compiled {builder_args.pte_path}")
RuntimeError: Failed to load ET compiled model.pte
(py311) mikekg@mikekg-mbp torchchat % 
```

**Comment by Jack-Khuu** [comment]
stale issue
