### ISSUE TITLE
Eval fails for stories15M.pte:   E 00:00:05.929516 executorch:method.cpp:820] Error setting input 0: 0x10 (PR #838)

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/torchchat#841]
https://github.com/pytorch/torchchat/actions/runs/9163587067/job/25193029015?pr=838

```
The methods are:  {'forward'}
  + python3 torchchat.py eval stories15M --pte-path stories15M.pte
  Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
  NumExpr defaulting to 8 threads.
  PyTorch version 2.4.0.dev20240507+cu121 available.
  Warning: checkpoint path ignored because an exported DSO or PTE path specified
  Using device=cpu
  Loading model...
  Time to load model: 0.02 seconds
  I 00:00:00.000856 executorch:program.cpp:129] InternalConsistency verification requested but not available
  -----------------------------------------------------------
  Detected kernel version 4.14.336, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
  Using device 'cpu'
  /opt/conda/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
    warnings.warn(
  [Task: wikitext] metric word_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
  [Task: wikitext] metric word_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
  [Task: wikitext] metric byte_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
  [Task: wikitext] metric byte_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
  [Task: wikitext] metric bits_per_byte is defined, but aggregation is not. using default aggregation=bits_per_byte
  [Task: wikitext] metric bits_per_byte is defined, but higher_is_better is not. using default higher_is_better=False
  /opt/conda/lib/python3.11/site-packages/datasets/load.py:1486: FutureWarning: The repository for EleutherAI/wikitext_document_level contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/EleutherAI/wikitext_document_level
  You can avoid this message in future by passing the argument `trust_remote_code=True`.
  Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
    warnings.warn(
  Repo card metadata block was not found. Setting CardData to empty.
  Repo card metadata block was not found. Setting CardData to empty.
  Building contexts for task on rank 0...
  Running loglikelihood_rolling requests
  
    0% 0/62 [00:00<?, ?it/s]E 00:00:05.929493 executorch:tensor_impl.cpp:86] Attempted to resize a static tensor to a new shape at dimension 1 old_size: 1 new_size: 1537
  E 00:00:05.929516 executorch:method.cpp:820] Error setting input 0: 0x10
  
    0% 0/62 [00:00<?, ?it/s]
  Time to run eval: 5.85s.
  Traceback (most recent call last):
    File "/pytorch/torchchat/torchchat.py", line 112, in <module>
      eval_main(args)
    File "/pytorch/torchchat/eval.py", line 245, in main
      result = eval(
               ^^^^^
    File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
      return func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/pytorch/torchchat/eval.py", line 192, in eval
      eval_results = evaluate(
                     ^^^^^^^^^
    File "/opt/conda/lib/python3.11/site-packages/lm_eval/utils.py", line 402, in _wrapper
      return fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/site-packages/lm_eval/evaluator.py", line 330, in evaluate
      resps = getattr(lm, reqtype)(cloned_reqs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/site-packages/lm_eval/models/huggingface.py", line 616, in loglikelihood_rolling
      string_nll = self._loglikelihood_tokens(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/site-packages/lm_eval/models/huggingface.py", line 787, in _loglikelihood_tokens
      self._model_call(batched_inps, **call_kwargs), dim=-1
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/pytorch/torchchat/eval.py", line 145, in _model_call
      logits = model_forward(self._model, x, input_pos)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/pytorch/torchchat/generate.py", line 260, in model_forward
      return model(x, input_pos)
             ^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      return forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/pytorch/torchchat/build/model_et.py", line 15, in forward
      logits = self.model_.forward(forward_inputs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  RuntimeError: method->set_inputs() for method 'forward' failed with error 0x12
  Error: Process completed with exit code 1.
0s
0s
1s
```

**Comment by Jack-Khuu** [comment]
Closing old issues
