### ISSUE TITLE
Failed to build wheel for executorch. Failed to stat buck-out/v2

### ISSUE THREAD

**Issue by WaelShaikh** [pytorch/torchchat#990]
### 🐛 Describe the bug

While running the command:

`./scripts/install_et.sh`

I get:

```
  -- Using python executable '/usr/bin/python3'
  -- Resolved buck2 as /mnt/d/TorchChat/et-build/src/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/buck2-bin/buck2-3bbde7daa94987db468d021ad625bc93dc62ba7fcb16945cb09b64aab077f284.
  -- Killing buck2 daemon
  -- executorch: Generating source lists
  -- executorch: Generating source file list /mnt/d/TorchChat/et-build/src/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/executorch_srcs.cmake
  Error while generating /mnt/d/TorchChat/et-build/src/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/executorch_srcs.cmake. Exit code: 1
  Output:

  Error:
  Traceback (most recent call last):
    File "/mnt/d/TorchChat/et-build/src/executorch/build/buck_util.py", line 26, in run
      cp: subprocess.CompletedProcess = subprocess.run(
    File "/usr/lib/python3.10/subprocess.py", line 526, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['/mnt/d/TorchChat/et-build/src/executorch/pip-out/temp.linux-x86_64-cpython-310/cmake-out/buck2-bin/buck2-3bbde7daa94987db468d021ad625bc93dc62ba7fcb16945cb09b64aab077f284', 'cquery', "inputs(deps('//runtime/executor:program'))"]' returned non-zero exit status 2.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/mnt/d/TorchChat/et-build/src/executorch/build/extract_sources.py", line 218, in <module>
      main()
    File "/mnt/d/TorchChat/et-build/src/executorch/build/extract_sources.py", line 203, in main
      target_to_srcs[name] = sorted(target.get_sources(graph, runner))
    File "/mnt/d/TorchChat/et-build/src/executorch/build/extract_sources.py", line 116, in get_sources
      sources: set[str] = set(runner.run(["cquery", query]))
    File "/mnt/d/TorchChat/et-build/src/executorch/build/buck_util.py", line 31, in run
      raise RuntimeError(ex.stderr.decode("utf-8")) from ex
  RuntimeError: Command failed:
  Error validating working directory

  Caused by:
      0: Failed to stat `/mnt/d/TorchChat/et-build/src/executorch/buck-out/v2`
      1: ENOENT: No such file or directory


  CMake Error at build/Utils.cmake:191 (message):
    executorch: source list generation failed
  Call Stack (most recent call first):
    CMakeLists.txt:327 (extract_sources)


  -- Configuring incomplete, errors occurred!
  error: command '/home/wael/.local/bin/cmake' failed with exit code 1
  error: subprocess-exited-with-error

  × Building wheel for executorch (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /home/wael/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpex1c4j5p
  cwd: /mnt/d/TorchChat/et-build/src/executorch
  Building wheel for executorch (pyproject.toml) ... error
  ERROR: Failed building wheel for executorch
Failed to build executorch
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (executorch)
```

### Versions

My env is so bad even this script erros out. I'm on WSL btw.

```
Collecting environment information...
Traceback (most recent call last):
  File "/mnt/d/TorchChat/collect_env.py", line 651, in <module>
    main()
  File "/mnt/d/TorchChat/collect_env.py", line 634, in main
    output = get_pretty_env_info()
  File "/mnt/d/TorchChat/collect_env.py", line 629, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "/mnt/d/TorchChat/collect_env.py", line 454, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
  File "/mnt/d/TorchChat/collect_env.py", line 411, in get_pip_packages
    out = run_with_pip([sys.executable, '-mpip'])
  File "/mnt/d/TorchChat/collect_env.py", line 406, in run_with_pip
    for line in out.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

**Comment by Jack-Khuu** [comment]
Hi @WaelShaikh, thanks for testing out the repo!

We've been focusing on development support mainly for Macs and Linux, but Windows/WSL support is definitely something we plan on looking into in the future.

**Comment by sunshinesfbay** [comment]
Looks very similar to #985

**Comment by Jack-Khuu** [comment]
@WaelShaikh  To help align the investigation, let's merge this with https://github.com/pytorch/torchchat/issues/985

**Comment by lherrera-db** [comment]
I am getting the same error on a Mac Apple M1 Pro, Sonoma 14.4.1
